language: python

python:
  - '3.6'

install:
  - pip install -U pytest pytest-cov codecov flake8
  - pip install -e .

script:
  - pytest --cov
  - python3 -m flake8 --exclude=build,doc,example,tmp

after_success:
  - codecov

deploy:
  provider: pypi
  user: dweindl
  password:
    secure: WSGm9+c67bc9GzEq0qfxFN1qUVUP32OZwHSM6BPlIdvMvo0cOxiJIvmrgufpmBnxqxytvTOc9NVNUYp3INbo8x4ohI8hbUw8liwQypb6fakWvWKDEdLhu7xaIyJh/QP0aVnxMlq+RHypP+iYImDJW6Ss3WghINpln+vd9gv2O4vAdywCzrnI4VXO90mkTSFmEFFZnyAvA5Ht0zFaL+Mh0+Ggzo1/PDXCvQ9nLr07HaYAf3UG3SdQX8s1zSN67iu9+hchTefzm/Eq9pSpz+8ZhIdidvNnYv4zyJ5xtMKpL+5TQrl/7BDMM1UameJbDgG724bn53nuEL7fY1T1eguUt4m29cLl8QXidahLmNspnLkZmAWt6xixTAeEkUeGzsWnWxgsHf3fyy+gzAbD7i22vFlirym4l0ZkTcdtiuFRe3uNmVMHf5O3jgilc313odit5AWRJCLJINaZ3sMVZc3prMYC1w4FJuPI9WKnZJYJuKyhP8680fCkcQQmRdQ3zJqnwgQcUBCkY02L1dJdhUvwcAnAUHwu0Fb/hE1vdb75BQ9V78oeM9kzpF+inNxNWgrZVXH6dG6NN4naPL2W2WH3Oq7k6ib/qqmk7OE+FhFpjq+Gv2oY93qRHvb4djPEZVDLwFmz9y0Vdx1e2YRCnVor1pQbqPgIc/V+dmC6V4UhIhI=
  on:
    branch: master
    tags: true
