language: python
python:
  - "3.6"

install:
  - pip install -U pytest pytest-cov codecov flake8 pickle
  - pip install -e .

script:
  - pytest --cov
  - python3 -m flake8 --exclude=build,doc,example,tmp

after_success:
  - codecov
