language: python

python:
  - '3.6'

install:
  - pip install -U pytest pytest-cov codecov flake8
  - pip install -e .

script:
  - pytest --cov
  - python3 -m flake8 --exclude=build,doc,example,tmp

after_success:
  - codecov

deploy:
  provider: pypi
  user: dweindl
  password:
    secure: MF4TXxu29fhh6RaL3Kz4hMsDe+FSI2iMVyOZa3ahREd3grK5WVsPy4bQ2ykQotRkvW2hiqx8ffVK9XXYd7MTmGahv85lASdqquVhT+8P6ZWEShSRRQ1V6QI2QrPNQBQoyTdXWodeR/ys25FwwvaYn1Inmd3CiNXFEA0sW/YnH5sZhWZtc05Vl57rzkFnLQ0Vn85o/fn14OQGw1QO6XU6ZTOnnP5jl4hVE5OypqyEqEVoQxQtE6/uRjAlJ1aTdHIhuEz8DWcIhmJTQWaipMqufQEzQrWMPnzM+4r8IsAbcfGf1nqQRmayLxx1x7PzRBWGukbOgCPNeRFNH2Z55FhIyDmeqcmD++id6yvHuPTAvsCCR6xmeg41R50YQ+Xax++BFNMizP38tYs0eqsqMRXXrUvMf0ap4HFPUSDgiTzS0iet7o8tA/EDfVadCfSHVUw19PAATxMDXB1/cjG3BC392Aw24mERnZ99p354WD2d1xteWspN6Nl43LRwk+lGHE8Wa/y9M1tu3dpATWtZNmdB9pp5Pa8kgXwpiOY2pPFJbY2Iet81yO3CifPy5C3kD3UI8xAXFaNduob86oA98GMZJ7LOY/NDBMbBkl8p5Pqxm0UmzvzFKcULMPZE3ce7r9/BpBed+bO+Z4HqQLlLbNAuG37+gWzEp9vbcLW7lPzZks8=
  on:
    branch: master
    tags: true
